### ISSUE TITLE
Building on Windows with MinGW

### ISSUE THREAD

**Issue by CounterPillow** [D-Programming-Deimos/ncurses#16]
The modules requires the static library "ncursesw.lib", however, it would be great if I could use a DLL so I can use a MinGW compiled version. (This is the recommended way of compiling ncurses on Windows).

I've been successful in compiling ncursesw (both static and shared) for Windows with MinGW, all that's stopping me from some silly console madness is the fact that it tries to link "ncursesw.lib" now, which would require the Microsoft Visual C/++ toolchain.

**Comment by CyberShadow** [comment]
As this issue is approaching a decade in age, and with the landscape of POSIX implementations for Windows having changed quite a bit, I'm going to close this issue. Please open new issues for any problems which can be easily reproduced today. Thanks!
