### ISSUE TITLE
Duplicate symbols _COLORS, _COLOR_PAIRS, etc.

### ISSUE THREAD

**Issue by Verdagon** [D-Programming-Deimos/ncurses#18]
Hey, I'm compiling on OSX 10.8.5, I just installed ncursesw, and I'm trying to get the examples to work, but it doesn't quite like me:

tachyon7:examples Verdagon$ make simpleColor
rdmd -g -w --build-only -ofbin/simpleColor -I../ -L-lncursesw simpleColor.d
duplicate symbol _COLORS in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_color.o)
duplicate symbol _COLOR_PAIRS in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_color.o)
duplicate symbol _ESCDELAY in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_getch.o)
duplicate symbol _ripoffline in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_set_term.o)
duplicate symbol _acs_map in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_acs.o)
duplicate symbol _stdscr in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_data.o)
duplicate symbol _curscr in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_data.o)
duplicate symbol _newscr in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_data.o)
duplicate symbol _TABSIZE in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_setup.o)
duplicate symbol _ttytype in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_setup.o)
duplicate symbol _LINES in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_setup.o)
duplicate symbol _COLS in:
    /tmp/.rdmd-501/rdmd-simpleColor.d-9EEE0B8638A612107715C3933A16A363/objs/simpleColor.o
    /usr/local/lib/libncursesw.a(lib_setup.o)
ld: 12 duplicate symbols for architecture x86_64
collect2: ld returned 1 exit status
--- errorlevel 1
make: **\* [simpleColor] Error 1
tachyon7:examples Verdagon$ 

Is this a bug or am I doing something wrong? Thanks!

**Comment by jaydg** [comment]
This issue can be closed, it no longer applies. Building on OS X is fully supported since 042c5a09.
