### ISSUE TITLE
Package format issue.

### ISSUE THREAD

**Issue by APott** [D-Programming-Deimos/ncurses#19]
Hello!
It is mentioned in the [dub package format](http://code.dlang.org/package-format#build-settings) that it is best to use `importPaths` rather than or with `sourcePaths` in package.json. Dub is also giving me a warning while building with this due to this issue.

```
Package ncurses (configuration "library") defines no import paths, use {"importPaths": [...]} or the default package directory structure to fix this.
```

I found the best way to prevent this is to use both as suggested, like the following:

``` json
...
"sourcePaths": [
    "deimos"
],
"importPaths": [
    "deimos"
],
...
```

**Comment by jaydg** [comment]
This issue can be closed, it was resolved with 2ee761c4.
