### ISSUE TITLE
Release date

### ISSUE THREAD

**Issue by yisonPylkita** [D-Programming-Deimos/ncurses#25]
When will be there a first release ?

**Comment by yisonPylkita** [comment]
Thanks for reply.
According to `dub.json` file specification using a git branch as a version is deprecated
Use a GIT branch (deprecated): "~master"`.
So here is my question, when will be there first release, so I can use it to import this library/wrapper ?

**Comment by CyberShadow** [comment]
Most Deimos repositories are entirely driven by volunteer contributions, so feel free to create a PR making the necessary change to the Dub package.

**Comment by dejlek** [comment]
In theory we can make deimos-ncurses have the same versions as the upstream...

**Comment by CyberShadow** [comment]
I created two tags, v0.0.141 and v0.0.148 (before and after merging open PRs).
