### ISSUE TITLE
D acs_vars example no longer shows expected characters

### ISSUE THREAD

**Issue by Griffon26** [D-Programming-Deimos/ncurses#30]
The acs chars I use for drawing boxes no longer appear to work. It's hard to pinpoint which upgrade caused this regression on my system (compiler, deimos/ncurses, ncurses, etc), but currently the C acs_vars example works properly and the equivalent D example doesn't.

This is what the output from the D version looks like on my system:
```
Upper left corner           ^A
Lower left corner           P
Lower right corner          ^@
Tee pointing right          ^@
Tee pointing left           ^@
Tee pointing up             ^@
Tee pointing down           ^@
Horizontal line              
Vertical line               ^@
Large Plus or cross over    ^@
Scan Line 1                 ^@
Scan Line 3                 ^A
Scan Line 7                 ^A
Scan Line 9                 (
Diamond                     ^@
Checker board (stipple)     ^@
Degree Symbol               ^@
Plus/Minus Symbol           ^@
Bullet                      ^@
Arrow Pointing Left         ≠
Arrow Pointing Right        +
Arrow Pointing Down         \
Arrow Pointing Up           Z
Board of squares            ^@
Lantern Symbol              ^@
Solid Square Block          ◆
Less/Equal sign             ^@
Greater/Equal sign          ^@
Pi                          ^@
Not equal                   ^@
UK pound sign               ^@
```

**Comment by Griffon26** [comment]
I've found the problem, but I'm not 100% sure of the fix. The problem is that ncurses' chtype is 4 bytes on my system, while the D bindings' chtype is 8 (c_ulong + dmd64), causing a lookup in acs_map to look at the wrong position.

I think that chtype is supposed to always be 32-bit, but I'm not sure about that. If so, then deimos should use uint instead of c_ulong.

**Comment by jaydg** [comment]
Could you please post your test code? This will help to reproduce and understand the issue.

**Comment by CyberShadow** [comment]
@jaydg This issue can be trivially reproduced by running `dub fetch ncurses && dub run ncurses:acs_vars`. Or did you mean some other form of test code?

**Comment by jaydg** [comment]
D'oh, you're right. Thorough reading definitely helps a lot!

**Comment by jaydg** [comment]
This one is really tricky. 

There was an ABI change in ncurses 6 that modifies the size of `chtype` and `mmask_t`. The example shows the expected characters when linked against a version 5 ncurses, whereas those type aliases need to be changed to `uint` from `c_ulong` to show the correct characters when linked against ncurses version 6.  

Excerpt from curses.h that comes with ncurses 5:
```
typedef unsigned long chtype;
typedef unsigned long mmask_t;
```

ncurses 6:
```
typedef uint32_t chtype;
typedef uint32_t mmask_t;
```

**Comment by dejlek** [comment]
From my Linux workstation:

    #if 0 && defined(_LP64)
    typedef unsigned chtype;
    typedef unsigned mmask_t;
    #else
    typedef unsigned long chtype;
    typedef unsigned long mmask_t;
    #endif

**Comment by CyberShadow** [comment]
Actually I think https://github.com/D-Programming-Deimos/ncurses/pull/45 gets us closer to where we want to be.
