### ISSUE TITLE
Failure to install on ppc64le

### ISSUE THREAD

**Issue by ArchaB** [D-Programming-Deimos/ncurses#31]
Hi,

I am trying to port ncurses package on Linux ppc64le Ubuntu VM.
But when I try to run the install command, it fails with an Unsupported Architecture Error

```
root@63225bb162be:/D-Programming-Deimos/ncurses# CURL_USER_AGENT="$CURL_USER_AGENT" bash install.sh dmd
Unsupported Arch ppc64le
```

Analysed the install.sh script, but failed to install dmd and dub in the container. 

Also tried installing dub from apt-get as mentioned in the url https://www.howtoinstall.co/en/ubuntu/xenial/dub, but it failed as unrecognized package.

```\root@63225bb162be:/D-Programming-Deimos/ncurses# apt-get install dub
Reading package lists... Done
Building dependency tree
Reading state information... Done
W: Target Packages (restricted/binary-ppc64el/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:36
W: Target Packages (restricted/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:4 and /etc/apt/sources.list:36
W: Target Packages (universe/binary-ppc64el/Packages) is configured multiple times in /etc/apt/sources.list:17 and /etc/apt/sources.list:36
W: Target Packages (universe/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:17 and /etc/apt/sources.list:36
E: Unable to locate package dub
```

Any pointer on what changes would be required in the install.sh to support the ppc64le architecture would be helpful. 

Regards,
Archa

**Comment by CyberShadow** [comment]
DMD can only target x86 and x86_64. Please try a D compiler with a backend supporting ppc64le, such as GDC or LDC.
