### ISSUE TITLE
Any way so that I press the up arrow key and a function executes?

### ISSUE THREAD

**Issue by pratimaupadhyay02** [D-Programming-Deimos/ncurses#34]
Hi
I wanted to know if there is a way to use ncurses in such a way that I press any key and a function of my choice executes. I tried multiple times in c but all i get is a blank screen that returns to the original terminal after I press a key.

**Comment by CyberShadow** [comment]
```d
auto ch = getch();
switch (ch)
{
	case KEY_UP:
		myFunction();
		break;
	// ...
}
```
