### ISSUE TITLE
Problem with scanw ()

### ISSUE THREAD

**Issue by gabol997** [D-Programming-Deimos/ncurses#39]
### **the function scanw () is not working the compiler reports error at the time of compiling the code.**

Error: function deimos.ncurses.curses.scanw(char* fmt, ...) is not callable using argument types (string, int*)
source/app.d(11,14):        cannot pass argument "0" of type string to parameter char* fmt
/usr/bin/dmd failed with exit code 1.

**Comment by CyberShadow** [comment]
You generally cannot directly pass D strings to C functions. You need to convert them to a zero-terminated string instead.

Please ask future questions on using D at https://forum.dlang.org/group/learn.

**Comment by gabol997** [comment]
you could solve this error by setting the constant in int scant(char * fmt, ...);
